### ISSUE TITLE
node-gyp rebuild failed on OSX

### ISSUE THREAD

**Issue by DragosDumitrache** [kloni/node-prolog-swi#6]
Try running the install command with npm and this is the output I get. SWI_HOME_DIR is set to the correct path. Any idea what could be the issue?

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dragos/Workspace/hack/ArgTeach/node_modules/node-prolog-swi
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-prolog-swi"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-prolog-swi@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-prolog-swi@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-prolog-swi package,
npm ERR! not with npm itself.
```

**Comment by kloni** [comment]
Maybe you wanna try the OSX fix suggested here https://github.com/sandeepmistry/bleno/issues/107 .

> ... can you please try creating a src/dummy.c with an empty main method.
> 
> Then adding something like this to the binding.gyp:
> 
> ```
>   ['OS=="mac"', {
>      'sources': [
>        'src/dummy.c'
>      ]
>    }]
> ```
> 
> ...

**Comment by DragosDumitrache** [comment]
Hello,

I've added the line and created the dummy.c. Now, node-gyp clean and node-gyp configure both work, but I still get a semantic error when running node-gyp build.

Here's my binding.gyp file:

```
{
  "targets": [
    {
      "target_name": "libswipl",
      "product_prefix": "lib",
      "sources": [
        "./src/libswipl.cc"
      ],
      "include_dirs": [
        "./src",
        "$(SWI_HOME_DIR)"
      ],
      "direct_dependent_settings": {
        "linkflags": [
          "-D_FILE_OFFSET_BITS=64",
          "-D_LARGEFILE_SOURCE"
        ]
      },
      "libraries": [
        "-lswipl"
      ],
      "conditions": [
        ['OS=="mac"', {
          'sources': [
            './src/dummy.c'
          ]
        }]
      ]
    }
  ]
}
```

**Comment by DragosDumitrache** [comment]
Downgraded to a lower version of node and now it's no longer complaining about errors in the .cc and .h files. However, build still gives the following error, since it can't find -lswipl. I may be doing something wrong, so if you could point me in the right direction, I'd appreciate it.

```
ld: library not found for -lswipl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/libswipl.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)

```

**Comment by mikeyakymenko** [comment]
Same problem.

**Comment by DragosDumitrache** [comment]
@mikeyakimenko I myself gave up on this as it's a problem with the newer versions of node and npm. They changed something, haven't tracked down what exactly that was, and the current version of the package no longer works. Looked into Ruby alternatives, but no luck there either, so I ended up translating the Prolog into JS

**Comment by mikeyakymenko** [comment]
@DragosDumitrache  Also i solve this problem use very old version.

`nvm use 0.12.7` and every thing ok. But, i guess this is not a good solution?

**Comment by DragosDumitrache** [comment]
@mikeyakimenko If that works for you, I suppose you can use it. Not sure about future maintenance though. It was clashing with a few other packages I was using, which resulted in me just translating the whole thing.

**Comment by raghavio** [comment]
Hey, @mikeyakimenko.
I'm stuck with this too. Can you tell me which npm & node version to use to make this work?

Thanks.
